artifacts:
  stackoverflow-dataset:
    path: data/raw/data.xml
    type: dataset
    desc: Initial XML StackOverflow dataset (raw data)
  text-classification:
    path: model.pkl
    desc: Detect whether the given stackoverflow question should have R language tag
    type: model
    labels:
      - nlp
      - classification
      - stackoverflow
stages:
  prepare:
    cmd: python src/prepare.py data/raw/data.xml
    deps:
      - data/raw/data.xml
      - src/prepare.py
    params:
      - prepare.seed
      - prepare.split
    outs:
      - data/interim/train.tsv
      - data/interim/test.tsv
  featurize:
    cmd: python src/featurization.py data/interim data/processed/features
    deps:
      - data/interim
      - src/featurization.py
    params:
      - featurize.max_features
      - featurize.ngrams
    outs:
      - data/processed/features
  train:
    cmd: python src/train.py data/processed/features models/model.pkl
    deps:
      - data/processed/features
      - src/train.py
    params:
      - train.min_split
      - train.n_est
      - train.seed
    outs:
      - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py models/model.pkl data/processed/features
    deps:
      - data/processed/features
      - models/model.pkl
      - src/evaluate.py
    outs:
      - eval
metrics:
  - eval/metrics.json
plots:
  - ROC:
      template: simple
      x: fpr
      y:
        eval/plots/sklearn/roc/train.json: tpr
        eval/plots/sklearn/roc/test.json: tpr
  - Confusion-Matrix:
      template: confusion
      x: actual
      y:
        eval/plots/sklearn/cm/train.json: predicted
        eval/plots/sklearn/cm/test.json: predicted
  - Precision-Recall:
      template: simple
      x: recall
      y:
        eval/plots/sklearn/prc/train.json: precision
        eval/plots/sklearn/prc/test.json: precision
  - eval/plots/images/importance.png
