[tool.poetry]
name = "hundzula-2024-reproducible-nlp"
version = "0.1.0"
description = ""
authors = ["ndamulelo <nbanzyme@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
